### ISSUE TITLE
NIO provides basic async/await API already

### ISSUE THREAD

**Issue by weissi** [GeorgeLyon/Shwift#1]
https://github.com/GeorgeLyon/Shwift/blob/8fb57012a1555cdd62243ac6504018f9b6fcddd5/Sources/Shwift/NIO.swift#L5

They are :). If you `import _NIOConcurrency`, then you should be able to just use `try await channel.close()`.  `EventLoopFuture` also has `func get() async throws`, and `EventLoopPromise` can be fulfilled with an `async` computation.

--> https://github.com/apple/swift-nio/blob/main/Sources/_NIOConcurrency/AsyncAwaitSupport.swift

**Comment by GeorgeLyon** [comment]
Thanks!
