### ISSUE TITLE
Feature: Allow splitting on something other than '\n'

### ISSUE THREAD

**Issue by wti** [GeorgeLyon/Shwift#20]
I forked to optionally set the line-split character and shell working directory.   Would you be interested in separate PR's on point?  The changes can be API+behavior-compatible and testable.  

As you can imagine, splitting/chunking helps downstream tools that expect one record at a time, esp. for null-delimited output to avoid parsing ambiguity.  The working dir often forms an implicit context, esp. dev tools on source trees.  (I'm using both in a tool to parse git logs.)

<https://github.com/wti/Shwift/tree/eol-character>

If so, please let me know any non-obvious goals/constraints/concerns.

(And thanks for the package!)

**Comment by GeorgeLyon** [comment]
This is very useful additional functionality! Thank you for taking the time to submit it!

Your changes look solid, do you want to submit a PR? I have some nits that would be easier to discuss in that format. One high level comment is that I don't want to add `cwd` to `Script` as part of this change. There's probably something we can do to manage the working directory in a `Script` but I'd need to think more deeply about it (and `Script` is a thin wrapper over the actual functionality of `Shwift`, so in general I'm happy to add more functionality to `Shwift`, but want to keep `Script` as simple as possible). In the interim, `git` has a `-C` argument you can use that has roughly the same effect as changing the working directory.

**Comment by wti** [comment]
Yeah, re: cwd sorry I didn't notice `subshell(pushing: ...)`.

Also please ignore my current branch as mucked up with testing. 

I'll work up a clean PR for splitting, aiming to start with the fix and tests for #22 and ordering the remaining commits from least to most controversial.

**Comment by GeorgeLyon** [comment]
Ah I had missed that as well :)
