### ISSUE TITLE
Lines.makeAsyncIterator drops remainder when buffers have no delimiter

### ISSUE THREAD

**Issue by wti** [GeorgeLyon/Shwift#22]
Writing echo + map tests with delimiters, I stumbled on a data loss that might be relatively rare in practice.

In `Shwift.Builtin.Lines.makeAsyncIterator()`, if there are 2+ contiguous `buffer` from `byteBuffers` that contain no delimiter, the remainder from the first buffer will be lost when the second remainder is saved at the end of the loop. 

A fix is to use += to accumulate the remainder.

<https://github.com/GeorgeLyon/Shwift/blob/edc8e7651d50e92588cecd785755f19a41672d08/Sources/Shwift/Builtins.swift#L114>

```{swift}
public func makeAsyncIterator() -> AsyncIterator {
  ...
  do {
    var remainder: String = ""
    for try await buffer in byteBuffers {
      let readString = ...!
      var substring = readString[readString.startIndex...]
      while let lineBreak = substring.firstIndex(of: delimiter) {
         ..
         continuation.yield(remainder + String(line))
         remainder = ""
      }
      remainder = String(substring) // FIX: +=
    }
    if !remainder.isEmpty {
      continuation.yield(remainder)
    }
    ...
}
```

That seems like a priority over #20.  However, atm the only repeatable test I found is using a pipe from echo to map upgraded with delimiter and terminator.   

So (unless you'd like something else or can guide me to a Shwift-only test) I'll start that PR with just enough of the delimiters and tests to see the bug reproduced and fixed, in case you want to go ahead with the fix before we work through the delimiter implementation and its other tests.

**Comment by GeorgeLyon** [comment]
Fixed by https://github.com/GeorgeLyon/Shwift/pull/26

**Comment by wti** [comment]
Still outstanding? It looks like #26 initially had the `=` -> `+=` fix on `Shwift/Builtins.swift:133`, but it was reverted later when the tests were fixed: <https://github.com/GeorgeLyon/Shwift/pull/26/commits/0a049ef194c146423a7182780f604f81065218c1>

**Comment by GeorgeLyon** [comment]
Ah shoot, looks like you are correct, probably was too hasty with the git commands. I will fix this once I have a moment.
